spring:
  profiles: prod
server:
  tomcat:
    uri-encoding: utf-8
  ssl:
    key-store: classpath:sslhttps.jks
    key-store-password: 152821b95f451
    key-alias: www.gttview.club
    key-store-type: JKS
    enabled: true