spring:
  profiles: prod
server:
  tomcat:
    uri-encoding: utf-8
  ssl:
    key-store: classpath:www.gttview.club.jks
    key-store-password: g7he4ob533pwd4t
    key-alias: tomcat
    key-store-type: sun.security.provider.JavaKeyStore.JKS